# Genius Gambler {the nightmare of vegas}

#### Keywords

basketball, gambling, NBA, Las Vegas 

## Why bring machine learning to Las Vegas?

When it comes to gambling in basketball, Las Vegas expects people to be emotional. They love offering bets to an uninformed and irrational public. Vegas expect people to make unwise decisions based on emotion, ignorance, and arrogance. Gambling's structure and reputation has kept (most) smart people away. "Smart" people don't gamble because it is looked down upon and/or they recognize the risk-to-reward ratio is uninspiring and their chances of winning overtime is low. Genius Gambler brings smart people, or rather smart algorithms and models, to the world of basketball betting. 

## How does the model work?

Genius Gambler implements the latest machine learning algorithms used at Google, Facebook, and Uber to isolate the most promising (i.e., underpriced) bets concerning NBA games and players.
The steps of the model are: 
1. *Gather the data*:
Genius Gambler relies on a wide variety of publicly available and privately sold data. We gather all types of standard player and team statistics, including advanced statistics (which are themselves complicated models). Genius Gambler uses a variety of team-centric data, such as team schedules, stadium success, and amount of travel time between games. Additionally, Genius Gambler analyzes the internet for a variety of helpful insights, such as breaking news, twitter feeds, and online predictions by reputable sources. 

2. *Model team/player success*:
This "Success Model" uses machine learning techniques to predict the success (or lack thereof) of teams and players in the NBA. The Success Model is trained on the diverse forms of collected data discussed above. The model predicts a wide variety of common basketball statistics, such as the likelihood of a team to win a given game (and by how many points) or the amount of rebounds a given player will get during a season. Most importantly, the success model provides a likelihood for all potential values for these statistics. These predictions are modeled independently of bets offered by the casinos.

3. *Identify bets and gamble*:
Genius Gambler uses the results of the Success Model discussed above to place a value on all bets offered by mainstream Las Vegas casinos. In this final stage, we identify underpriced bets, combinations of underpriced bets (parlays), and arbitrage opportunities. Our model then determines, given our level of capital, the appropriate amount to gamble on a given underpriced bet.

## How did we do?

Last year, Genius Gambler started the season with $100,000 in capital and ended the season with just over $160,000 (60% return on investment). We outperformed most hedge funds by a significant margin. In total, we made 1,423 bets at an average price of $86.29 per bet. Our earnings were slightly skewed towards large earnings on low odds bets, as 60% of our profit came from 25% of our bets. Most of our losses came towards the end of the season as our model failed to recognize the general "wear and tear" on older players. Additionally, we learned that the NBA finals is too volatile to model with any great accuracy. As Genius Gambler is built with a machine learning framework, our algorithms will improve from last year and we expect even greater returns this year and into the future!
